# action.yml
name: 'Lime Build'
description: 'Build a haxe project with lime'
inputs:
  dir:
    description: 'The relative directory that the lime commands will take place in.  Defaults to ./'
    required: false
    default: './'
  platform:
    description: 'Type of lime build to run. Accepts html5|neko|macos|windows|flash|ios|android|linux.  See https://lime.software/docs/home/'
    required: false
    default: 'html5'
  buildArgs:
    description: 'Any extra build args to pass to the lime build call'
    required: false
    default: ''
  initScriptFile:
    description: 'A script to set up any needed code dependencies for the build'
    required: true
    default: './init.sh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.platform }}
    - ${{ inputs.buildArgs }}
    - ${{ inputs.initScriptFile }}