# action.yml
name: 'Lime Build'
description: 'Build a haxe project with lime'
inputs:
  dir:
    description: 'The relative directory that the lime commands will take place in.  Defaults to ./'
    required: false
    default: './'
  platform:
    description: 'Type of lime build to run. Accepts html5|neko|macos|windows|flash|ios|android|linux.  See https://lime.software/docs/home/'
    required: false
    default: 'html5'
  buildArgs:
    description: 'Any extra build args to pass to the lime build call'
    required: false
    default: ''
  gitDependencies:
    description: 'A list of haxelib dependencies that are gathered through git links.  Separated by | . See https://lib.haxe.org/documentation/using-haxelib/#git for more.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.platform }}
    - ${{ inputs.buildArgs }}
    - ${{ inputs.gitDependencies }}